# Exclude commonly ignored directories
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Black-like defaults
line-length = 88
indent-width = 4

# Infer from pyproject.toml: project.requires-python
# target-version = "py37"

[lint]
# Enable Pyflakes (`F`) and a subset of pycodestyle (`E`) codes by default
select = ["E4", "E7", "E9", "F"]
ignore = []

# Allow fix for all enabled rules when `--fix` is provided
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Use double quotes, spaces for indentation, magic trailing commas, and auto-detect line ending
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
